// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IP struct {
	// @inject_tag: valid:"ip" yaml:"ip" json:"overrided"
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IP) Reset()         { *m = IP{} }
func (m *IP) String() string { return proto.CompactTextString(m) }
func (*IP) ProtoMessage()    {}
func (*IP) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *IP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IP.Unmarshal(m, b)
}
func (m *IP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IP.Marshal(b, m, deterministic)
}
func (m *IP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IP.Merge(m, src)
}
func (m *IP) XXX_Size() int {
	return xxx_messageInfo_IP.Size(m)
}
func (m *IP) XXX_DiscardUnknown() {
	xxx_messageInfo_IP.DiscardUnknown(m)
}

var xxx_messageInfo_IP proto.InternalMessageInfo

func (m *IP) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type URL struct {
	// @inject_tag: valid:"http|https"
	Scheme string `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// @inject_tag: valid:"nonzero"
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URL) Reset()         { *m = URL{} }
func (m *URL) String() string { return proto.CompactTextString(m) }
func (*URL) ProtoMessage()    {}
func (*URL) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *URL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URL.Unmarshal(m, b)
}
func (m *URL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URL.Marshal(b, m, deterministic)
}
func (m *URL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URL.Merge(m, src)
}
func (m *URL) XXX_Size() int {
	return xxx_messageInfo_URL.Size(m)
}
func (m *URL) XXX_DiscardUnknown() {
	xxx_messageInfo_URL.DiscardUnknown(m)
}

var xxx_messageInfo_URL proto.InternalMessageInfo

func (m *URL) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *URL) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *URL) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Foobar struct {
	// @inject_tag_oneof: foo: validate:"non-zero"
	//
	// Types that are valid to be assigned to Data:
	//	*Foobar_Foo_
	//	*Foobar_Bar_
	Data                 isFoobar_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Foobar) Reset()         { *m = Foobar{} }
func (m *Foobar) String() string { return proto.CompactTextString(m) }
func (*Foobar) ProtoMessage()    {}
func (*Foobar) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *Foobar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foobar.Unmarshal(m, b)
}
func (m *Foobar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foobar.Marshal(b, m, deterministic)
}
func (m *Foobar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foobar.Merge(m, src)
}
func (m *Foobar) XXX_Size() int {
	return xxx_messageInfo_Foobar.Size(m)
}
func (m *Foobar) XXX_DiscardUnknown() {
	xxx_messageInfo_Foobar.DiscardUnknown(m)
}

var xxx_messageInfo_Foobar proto.InternalMessageInfo

type isFoobar_Data interface {
	isFoobar_Data()
}

type Foobar_Foo_ struct {
	Foo *Foobar_Foo `protobuf:"bytes,2,opt,name=foo,proto3,oneof"`
}

type Foobar_Bar_ struct {
	Bar *Foobar_Bar `protobuf:"bytes,3,opt,name=bar,proto3,oneof"`
}

func (*Foobar_Foo_) isFoobar_Data() {}

func (*Foobar_Bar_) isFoobar_Data() {}

func (m *Foobar) GetData() isFoobar_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Foobar) GetFoo() *Foobar_Foo {
	if x, ok := m.GetData().(*Foobar_Foo_); ok {
		return x.Foo
	}
	return nil
}

func (m *Foobar) GetBar() *Foobar_Bar {
	if x, ok := m.GetData().(*Foobar_Bar_); ok {
		return x.Bar
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Foobar) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Foobar_Foo_)(nil),
		(*Foobar_Bar_)(nil),
	}
}

type Foobar_Foo struct {
	Foo                  int32    `protobuf:"varint,1,opt,name=foo,proto3" json:"foo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foobar_Foo) Reset()         { *m = Foobar_Foo{} }
func (m *Foobar_Foo) String() string { return proto.CompactTextString(m) }
func (*Foobar_Foo) ProtoMessage()    {}
func (*Foobar_Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2, 0}
}

func (m *Foobar_Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foobar_Foo.Unmarshal(m, b)
}
func (m *Foobar_Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foobar_Foo.Marshal(b, m, deterministic)
}
func (m *Foobar_Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foobar_Foo.Merge(m, src)
}
func (m *Foobar_Foo) XXX_Size() int {
	return xxx_messageInfo_Foobar_Foo.Size(m)
}
func (m *Foobar_Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foobar_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foobar_Foo proto.InternalMessageInfo

func (m *Foobar_Foo) GetFoo() int32 {
	if m != nil {
		return m.Foo
	}
	return 0
}

type Foobar_Bar struct {
	Bar                  string   `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foobar_Bar) Reset()         { *m = Foobar_Bar{} }
func (m *Foobar_Bar) String() string { return proto.CompactTextString(m) }
func (*Foobar_Bar) ProtoMessage()    {}
func (*Foobar_Bar) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2, 1}
}

func (m *Foobar_Bar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foobar_Bar.Unmarshal(m, b)
}
func (m *Foobar_Bar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foobar_Bar.Marshal(b, m, deterministic)
}
func (m *Foobar_Bar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foobar_Bar.Merge(m, src)
}
func (m *Foobar_Bar) XXX_Size() int {
	return xxx_messageInfo_Foobar_Bar.Size(m)
}
func (m *Foobar_Bar) XXX_DiscardUnknown() {
	xxx_messageInfo_Foobar_Bar.DiscardUnknown(m)
}

var xxx_messageInfo_Foobar_Bar proto.InternalMessageInfo

func (m *Foobar_Bar) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

type ErrorFoo struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// @inject_tag: validate:"dive,required"
	Details              []*any.Any `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ErrorFoo) Reset()         { *m = ErrorFoo{} }
func (m *ErrorFoo) String() string { return proto.CompactTextString(m) }
func (*ErrorFoo) ProtoMessage()    {}
func (*ErrorFoo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *ErrorFoo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorFoo.Unmarshal(m, b)
}
func (m *ErrorFoo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorFoo.Marshal(b, m, deterministic)
}
func (m *ErrorFoo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorFoo.Merge(m, src)
}
func (m *ErrorFoo) XXX_Size() int {
	return xxx_messageInfo_ErrorFoo.Size(m)
}
func (m *ErrorFoo) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorFoo.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorFoo proto.InternalMessageInfo

func (m *ErrorFoo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorFoo) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type BarOpen struct {
	// @inject_tag_oneof: foo: validate:"non-zero"
	// @inject_tag_oneof: bar: validate:"required"
	// @inject_tag_oneof: baz: validate:"uuidv4"
	// @inject_tag: validate:"required"
	//
	// Types that are valid to be assigned to Data:
	//	*BarOpen_Foo
	//	*BarOpen_Bar
	//	*BarOpen_Baz
	Data                 isBarOpen_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BarOpen) Reset()         { *m = BarOpen{} }
func (m *BarOpen) String() string { return proto.CompactTextString(m) }
func (*BarOpen) ProtoMessage()    {}
func (*BarOpen) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *BarOpen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarOpen.Unmarshal(m, b)
}
func (m *BarOpen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarOpen.Marshal(b, m, deterministic)
}
func (m *BarOpen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarOpen.Merge(m, src)
}
func (m *BarOpen) XXX_Size() int {
	return xxx_messageInfo_BarOpen.Size(m)
}
func (m *BarOpen) XXX_DiscardUnknown() {
	xxx_messageInfo_BarOpen.DiscardUnknown(m)
}

var xxx_messageInfo_BarOpen proto.InternalMessageInfo

type isBarOpen_Data interface {
	isBarOpen_Data()
}

type BarOpen_Foo struct {
	Foo int32 `protobuf:"varint,1,opt,name=foo,proto3,oneof"`
}

type BarOpen_Bar struct {
	Bar string `protobuf:"bytes,2,opt,name=bar,proto3,oneof"`
}

type BarOpen_Baz struct {
	Baz int32 `protobuf:"varint,3,opt,name=baz,proto3,oneof"`
}

func (*BarOpen_Foo) isBarOpen_Data() {}

func (*BarOpen_Bar) isBarOpen_Data() {}

func (*BarOpen_Baz) isBarOpen_Data() {}

func (m *BarOpen) GetData() isBarOpen_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BarOpen) GetFoo() int32 {
	if x, ok := m.GetData().(*BarOpen_Foo); ok {
		return x.Foo
	}
	return 0
}

func (m *BarOpen) GetBar() string {
	if x, ok := m.GetData().(*BarOpen_Bar); ok {
		return x.Bar
	}
	return ""
}

func (m *BarOpen) GetBaz() int32 {
	if x, ok := m.GetData().(*BarOpen_Baz); ok {
		return x.Baz
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BarOpen) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BarOpen_Foo)(nil),
		(*BarOpen_Bar)(nil),
		(*BarOpen_Baz)(nil),
	}
}

type Person struct {
	// @inject_tag: validate:"required"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// @inject_tag: validate:"positive"
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{5}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*IP)(nil), "pb.IP")
	proto.RegisterType((*URL)(nil), "pb.URL")
	proto.RegisterType((*Foobar)(nil), "pb.foobar")
	proto.RegisterType((*Foobar_Foo)(nil), "pb.foobar.Foo")
	proto.RegisterType((*Foobar_Bar)(nil), "pb.foobar.Bar")
	proto.RegisterType((*ErrorFoo)(nil), "pb.errorFoo")
	proto.RegisterType((*BarOpen)(nil), "pb.BarOpen")
	proto.RegisterType((*Person)(nil), "pb.Person")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xd1, 0x4a, 0xeb, 0x40,
	0x10, 0xbd, 0x49, 0x7a, 0x93, 0x7b, 0xa7, 0x70, 0xb9, 0x2c, 0xa2, 0xb1, 0x0f, 0x52, 0xf2, 0xd4,
	0xa7, 0x2d, 0xd4, 0x2f, 0x68, 0x84, 0xa2, 0xa0, 0x58, 0x82, 0x7e, 0xc0, 0xac, 0xd9, 0x46, 0xa1,
	0xcd, 0x84, 0xd9, 0xf4, 0xa1, 0xfd, 0x04, 0xbf, 0x5a, 0x66, 0xb7, 0x29, 0xfa, 0x76, 0x66, 0xce,
	0xec, 0xd9, 0x73, 0x0e, 0x40, 0x6f, 0x5d, 0xaf, 0x3b, 0xa6, 0x9e, 0x54, 0xdc, 0x99, 0xc9, 0x75,
	0x43, 0xd4, 0x6c, 0xed, 0xdc, 0x6f, 0xcc, 0x7e, 0x33, 0xc7, 0xf6, 0x10, 0xe8, 0xe2, 0x06, 0xe2,
	0x87, 0xb5, 0xca, 0x21, 0x5b, 0xd6, 0x35, 0x5b, 0xe7, 0xf2, 0x68, 0x1a, 0xcd, 0xfe, 0x56, 0xc3,
	0x58, 0xdc, 0x41, 0xf2, 0x5a, 0x3d, 0xaa, 0x4b, 0x48, 0xdd, 0xdb, 0xbb, 0xdd, 0xd9, 0x13, 0x7f,
	0x9a, 0xd4, 0x7f, 0x48, 0xf6, 0xbc, 0xcd, 0x63, 0xbf, 0x14, 0xa8, 0x14, 0x8c, 0x3a, 0xe2, 0x3e,
	0x4f, 0xa6, 0xd1, 0xec, 0x77, 0xe5, 0x71, 0xf1, 0x19, 0x41, 0xba, 0x21, 0x32, 0xc8, 0xaa, 0x80,
	0x64, 0x43, 0xe4, 0x1f, 0x8c, 0x17, 0xff, 0x74, 0x67, 0x74, 0x20, 0xf4, 0x8a, 0xe8, 0xfe, 0x57,
	0x25, 0xa4, 0xdc, 0x18, 0x64, 0xaf, 0xf0, 0xf3, 0xa6, 0x44, 0x96, 0x1b, 0x83, 0x3c, 0xb9, 0x82,
	0x64, 0x45, 0x24, 0xff, 0x8b, 0x5c, 0xe4, 0x3f, 0x13, 0x28, 0x44, 0x89, 0x2c, 0x84, 0x68, 0x04,
	0xb7, 0x02, 0xcb, 0x14, 0x46, 0x35, 0xf6, 0x58, 0xbc, 0xc0, 0x1f, 0xcb, 0x4c, 0x2c, 0xcf, 0x73,
	0xc8, 0x76, 0xd6, 0x39, 0x6c, 0x86, 0x5c, 0xc3, 0xa8, 0x34, 0x64, 0xb5, 0xed, 0xf1, 0x63, 0xeb,
	0xf2, 0x78, 0x9a, 0xcc, 0xc6, 0x8b, 0x0b, 0x1d, 0x4a, 0xd4, 0x43, 0x89, 0x7a, 0xd9, 0x1e, 0xaa,
	0xe1, 0xa8, 0x78, 0x82, 0xac, 0x44, 0x7e, 0xee, 0x6c, 0xab, 0xd4, 0x37, 0x4f, 0x43, 0x24, 0x15,
	0xec, 0xf8, 0x9e, 0x4e, 0x11, 0xc2, 0xee, 0x18, 0x8a, 0x0a, 0xbb, 0xe3, 0xd9, 0xa4, 0x86, 0x74,
	0x6d, 0xd9, 0x91, 0xa8, 0x8d, 0x5a, 0x3c, 0xf7, 0xee, 0xb1, 0x84, 0x13, 0xcb, 0x71, 0x48, 0x8d,
	0x8d, 0x35, 0xa9, 0x77, 0x75, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0x76, 0xef, 0xd3, 0x9f, 0xfa,
	0x01, 0x00, 0x00,
}
